spring:
  profiles.active: native
  cloud.config.server.native.searchLocations: classpath:config/

server.port: 8888

encrypt.keyStore:
  location: classpath:server.jks
  password: letmein
  alias: mytestkey
  secret: changeme